/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Course
 */
export interface Course {
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    lectureName?: string;
    /**
     * 
     * @type {string}
     * @memberof Course
     */
    lectureCode?: string;
    /**
     * 
     * @type {number}
     * @memberof Course
     */
    lectureCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof Course
     */
    lectureGrade?: number;
}

/**
 * Check if a given object implements the Course interface.
 */
export function instanceOfCourse(value: object): value is Course {
    return true;
}

export function CourseFromJSON(json: any): Course {
    return CourseFromJSONTyped(json, false);
}

export function CourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Course {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lectureName': json['lectureName'] == null ? undefined : json['lectureName'],
        'lectureCode': json['lectureCode'] == null ? undefined : json['lectureCode'],
        'lectureCredit': json['lectureCredit'] == null ? undefined : json['lectureCredit'],
        'lectureGrade': json['lectureGrade'] == null ? undefined : json['lectureGrade'],
    };
}

export function CourseToJSON(json: any): Course {
    return CourseToJSONTyped(json, false);
}

export function CourseToJSONTyped(value?: Course | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lectureName': value['lectureName'],
        'lectureCode': value['lectureCode'],
        'lectureCredit': value['lectureCredit'],
        'lectureGrade': value['lectureGrade'],
    };
}

