apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: uos-easy-life
  name: uos-easy-life-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
