apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uos-easy-life-rolebinding
  namespace: uos-easy-life
subjects:
  - kind: ServiceAccount
    name: uos-easy-life-service-account
    namespace: uos-easy-life
roleRef:
  kind: Role
  name: uos-easy-life-role
  apiGroup: rbac.authorization.k8s.io
