/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAcademicStatusDTO
 */
export interface UserAcademicStatusDTO {
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    totalRequiredCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    totalCompletedCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    majorRequiredCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    majorCompletedCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    majorEssentialRequiredCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    majorEssentialCompletedCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    liberalRequiredCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    liberalCompletedCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    liberalEssentialRequiredCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    liberalEssentialCompletedCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    engineeringRequiredCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    engineeringCompletedCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    generalRequiredCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    generalCompletedCredit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    minimumTotalGradePointAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof UserAcademicStatusDTO
     */
    totalGradePointAverage?: number;
}

/**
 * Check if a given object implements the UserAcademicStatusDTO interface.
 */
export function instanceOfUserAcademicStatusDTO(value: object): value is UserAcademicStatusDTO {
    return true;
}

export function UserAcademicStatusDTOFromJSON(json: any): UserAcademicStatusDTO {
    return UserAcademicStatusDTOFromJSONTyped(json, false);
}

export function UserAcademicStatusDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAcademicStatusDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'totalRequiredCredit': json['totalRequiredCredit'] == null ? undefined : json['totalRequiredCredit'],
        'totalCompletedCredit': json['totalCompletedCredit'] == null ? undefined : json['totalCompletedCredit'],
        'majorRequiredCredit': json['majorRequiredCredit'] == null ? undefined : json['majorRequiredCredit'],
        'majorCompletedCredit': json['majorCompletedCredit'] == null ? undefined : json['majorCompletedCredit'],
        'majorEssentialRequiredCredit': json['majorEssentialRequiredCredit'] == null ? undefined : json['majorEssentialRequiredCredit'],
        'majorEssentialCompletedCredit': json['majorEssentialCompletedCredit'] == null ? undefined : json['majorEssentialCompletedCredit'],
        'liberalRequiredCredit': json['liberalRequiredCredit'] == null ? undefined : json['liberalRequiredCredit'],
        'liberalCompletedCredit': json['liberalCompletedCredit'] == null ? undefined : json['liberalCompletedCredit'],
        'liberalEssentialRequiredCredit': json['liberalEssentialRequiredCredit'] == null ? undefined : json['liberalEssentialRequiredCredit'],
        'liberalEssentialCompletedCredit': json['liberalEssentialCompletedCredit'] == null ? undefined : json['liberalEssentialCompletedCredit'],
        'engineeringRequiredCredit': json['engineeringRequiredCredit'] == null ? undefined : json['engineeringRequiredCredit'],
        'engineeringCompletedCredit': json['engineeringCompletedCredit'] == null ? undefined : json['engineeringCompletedCredit'],
        'generalRequiredCredit': json['generalRequiredCredit'] == null ? undefined : json['generalRequiredCredit'],
        'generalCompletedCredit': json['generalCompletedCredit'] == null ? undefined : json['generalCompletedCredit'],
        'minimumTotalGradePointAverage': json['minimumTotalGradePointAverage'] == null ? undefined : json['minimumTotalGradePointAverage'],
        'totalGradePointAverage': json['totalGradePointAverage'] == null ? undefined : json['totalGradePointAverage'],
    };
}

export function UserAcademicStatusDTOToJSON(json: any): UserAcademicStatusDTO {
    return UserAcademicStatusDTOToJSONTyped(json, false);
}

export function UserAcademicStatusDTOToJSONTyped(value?: UserAcademicStatusDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalRequiredCredit': value['totalRequiredCredit'],
        'totalCompletedCredit': value['totalCompletedCredit'],
        'majorRequiredCredit': value['majorRequiredCredit'],
        'majorCompletedCredit': value['majorCompletedCredit'],
        'majorEssentialRequiredCredit': value['majorEssentialRequiredCredit'],
        'majorEssentialCompletedCredit': value['majorEssentialCompletedCredit'],
        'liberalRequiredCredit': value['liberalRequiredCredit'],
        'liberalCompletedCredit': value['liberalCompletedCredit'],
        'liberalEssentialRequiredCredit': value['liberalEssentialRequiredCredit'],
        'liberalEssentialCompletedCredit': value['liberalEssentialCompletedCredit'],
        'engineeringRequiredCredit': value['engineeringRequiredCredit'],
        'engineeringCompletedCredit': value['engineeringCompletedCredit'],
        'generalRequiredCredit': value['generalRequiredCredit'],
        'generalCompletedCredit': value['generalCompletedCredit'],
        'minimumTotalGradePointAverage': value['minimumTotalGradePointAverage'],
        'totalGradePointAverage': value['totalGradePointAverage'],
    };
}

