#!/bin/bash
set -e
cd `dirname $0`/..
ROOT=`pwd`

cleanup() {
  echo -e "\rCleaning up..."
  pkill -P $$ || true
  echo "Done."
  exit 0
}

trap cleanup SIGINT SIGTERM

# Build the backend
build

# Start the backend
cd $ROOT/backend
java -jar build/libs/*-SNAPSHOT.jar&

# Start the frontend
cd $ROOT/frontend
yarn install
yarn dev&

# Sleep forever
while true; do
  sleep 1
done