#!/bin/bash
set -e
cd `dirname $0`/..
ROOT=`pwd`

cleanup() {
  echo -e "\rCleaning up..."
  pkill -P $$ || true
  docker-compose -f $ROOT/scripts/docker-compose.yaml down --volumes 2>&1 > /dev/null || true
  echo "Done."
  exit 0
}

trap cleanup SIGINT SIGTERM

# Start the containers using docker-compose
echo "Starting database and backend..."
docker-compose -f $ROOT/scripts/docker-compose.yaml up -d --build
echo "Database and backend started."

# Tail the logs of each service separately
docker-compose -f $ROOT/scripts/docker-compose.yaml logs -f mongodb > $ROOT/scripts/mongodb.log &
docker-compose -f $ROOT/scripts/docker-compose.yaml logs -f backend > $ROOT/scripts/backend.log &

# Install frontend dependencies
cd $ROOT/frontend
echo "Installing frontend dependencies..."
yarn install 2>&1 > /dev/null
echo "Frontend dependencies installed."

# Start the frontend
yarn dev 2>&1 > $ROOT/scripts/frontend.log&
echo "Frontend started."

tail -f $ROOT/scripts/mongodb.log $ROOT/scripts/backend.log $ROOT/scripts/frontend.log

# Sleep forever
while true; do
  sleep 1
done
